var CARDS_ARRAY = [
					{ 
						name:"Tiger",
						img:"",
						moves:[[-2,0],[1,0]]
					},
					{ 
						name:"Dragon",
						img:"",
						moves:[[-1,2],[-1,-2],[1,1],[1,-1]]
					},
					{ 
						name:"Frog",
						img:"",
						moves:[[0,-2],[-1,-1],[1,1]]
					},
					{ 
						name:"Rabbit",
						img:"",
						moves:[[0,2],[-1,1],[1,-1]]
					},
					{ 
						name:"Crab",
						img:"",
						moves:[[0,2],[0,-2],[-1,0]]
					},
					{ 
						name:"Elephant",
						img:"",
						moves:[[-1,1],[0,1],[-1,-1],[0,-1]]
					},
					{ 
						name:"Goose",
						img:"",
						moves:[[0,1],[0,-1],[1,1],[-1,-1]]
					},
					{ 
						name:"Rooster",
						img:"",
						moves:[[0,1],[0,-1],[-1,1],[1,-1]]
					},
					{ 
						name:"Monkey",
						img:"",
						moves:[[-1,1],[1,1],[1,-1],[-1,-1]]
					},
					{ 
						name:"Mantis",
						img:"",
						moves:[[-1,1],[-1,-1],[1,0]]
					},
					{ 
						name:"Horse",
						img:"",
						moves:[[-1,0],[1,0],[0,-1]]
					},
					{ 
						name:"Ox",
						img:"",
						moves:[[-1,0],[1,0],[0,1]]
					},
					{ 
						name:"Crane",
						img:"",
						moves:[[-1,0],[1,1],[1,-1]]
					},
					{ 
						name:"Boar",
						img:"",
						moves:[[0,1],[0,-1],[-1,0]]
					},
					{ 
						name:"Eel",
						img:"",
						moves:[[0,1],[-1,-1],[1,-1]]
					},
					{ 
						name:"Cobra",
						img:"",
						moves:[[-1,1],[1,1],[0,-1]]
					},
					{ 
						name:"Giraffe",
						img:"",
						moves:[[-1,2],[-1,-2],[1,0]]
					},
					{ 
						name:"Kirin",
						img:"",
						moves:[[-2,1],[-2,-1],[2,0]]
					},
					{ 
						name:"Phoenix",
						img:"",
						moves:[[0,2],[0,-2],[-1,1],[-1,-1]]
					},
					{ 
						name:"Turtle",
						img:"",
						moves:[[0,2],[0,-2],[1,1],[1,-1]]
					},
					{ 
						name:"Fox",
						img:"",
						moves:[[-1,1],[0,1],[1,1]]
					},
					{ 
						name:"Panda",
						img:"",
						moves:[[-1,1],[-1,0],[1,-1]]
					},
					{ 
						name:"Sea Snake",
						img:"",
						moves:[[-1,0],[0,2],[1,-1]]
					},
					{ 
						name:"Mouse",
						img:"",
						moves:[[0,1],[-1,0],[1,-1]]
					},
					{ 
						name:"Tanuki",
						img:"",
						moves:[[-1,0],[-1,2],[1,-1]]
					},
					{ 
						name:"Sable",
						img:"",
						moves:[[-1,1],[1,-1],[0,-2]]
					},
					{ 
						name:"Dog",
						img:"",
						moves:[[-1,-1],[0,-1],[1,-1]]
					},
					{ 
						name:"Bear",
						img:"",
						moves:[[-1,-1],[-1,0],[1,1]]
					},
					{ 
						name:"Viper",
						img:"",
						moves:[[-1,0],[0,-2],[1,1]]
					},
					{ 
						name:"Rat",
						img:"",
						moves:[[0,-1],[-1,0],[1,1]]
					},
					{ 
						name:"Iguana",
						img:"",
						moves:[[-1,0],[-1,-2],[1,1]]
					},
					{ 
						name:"Otter",
						img:"",
						moves:[[-1,-1],[1,1],[0,2]]
					}
				];